meta_product_name: "Experiment'Up"
meta_title: "Experiment'Up - Vivez des expériences inédites"
meta_description: "Découvrez des activités conviviales près de chez vous : des expériences, des rencontres pour illuminer votre quotidien"
meta_image: "boulognehome.png"                       # should exist in `app/assets/images/`
twitter_account: "@Experimentup_twitter_account"   # required for Twitter Cards
